---
- name: Set up Kubernetes cluster
  hosts: masters
  become: true
  vars:
    master_node: ec2-instance-1
  tasks:
    - name: Initialize Kubernetes master
      command: kubeadm init --apiserver-cert-extra-sans={{ master_node }} --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      when: inventory_hostname == master_node

    - name: Copy Kubernetes config to non-master nodes
      copy:
        content: "{{ hostvars[master_node]['kubeadm_output']['stdout_lines'] | select('match', '^kubeadm join') | list | join('\n') }}"
        dest: /root/kubeadm_join_command.sh
        mode: 0755
      when: inventory_hostname != master_node

    - name: Join non-master nodes to the cluster
      command: /root/kubeadm_join_command.sh
      when: inventory_hostname != master_node

    - name: Install Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: inventory_hostname == master_node

